#!/usr/bin/env bash
# Auto-generated by meshtools3d. Re-run this to reproduce the outputs.
'/Users/josealonsosolis-lemus/installs/meshtools3d-2.0.0-macos-arm64/bin/meshtools3d' '/Users/josealonsosolis-lemus/data/test_m3d/examples/sphereCoarse/sphere.par'
